services:
  db:
    image: postgis/postgis:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_HOST: ${DATABASE_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
